### ISSUE TITLE
[BUG] Missing smoke selector

### ISSUE THREAD

**Issue by CarlMichelsen** [asdf-dev/cs2iglClient#9] opened 2023-09-25 17:06 UTC
**Describe the bug**
smoke selector not showing up.

**To Reproduce**
Go to cs2igl.com
create lobby
have a friend join
reload page to see they joined
no smoke selector visible

**Expected behavior**
Smoke selector immidiatly visible

**Screenshots**
![image](https://github.com/asdf-dev/cs2iglClient/assets/29626285/54ef0d74-4bf0-4c04-8a7a-4ed10eab9817)

**Desktop (please complete the following information):**
 - Windows
 - Chrome and Edge
 - 117.0.5938.89 (Official Build) (64-bit) and windows 11

**Additional context**
Error related to grenade assignment in console

**Comment by asdf-dev** [comment] 2023-10-31 06:58
unable to reproduce in firefox. Still needs to be tested in chrome & steam browser

**Comment by asdf-dev** [comment] 2023-10-31 07:09
https://youtu.be/Y72TsnS5PyA Unable to reproduce closing bug

**Closed by asdf-dev** 2023-10-31 07:09 UTC
Labels: bug
